### ISSUE TITLE
regex - question mark

### ISSUE THREAD

**Issue by ihseko** [n1tr0-5urf3r/icinga2-discord-notifications#2]
apply Service "xxxxxxxxxxxxx" {
  vars.snmp_ereg = **"There are no failed disks"**
}

`'/etc/icinga2/scripts/discord-service-notification.sh' '-4' '1.1.1.1' '-6' '' '-b' 'admin' '-c' 'test' '-d' '2022-09-19 15:05:45 +0300' '-e' 'Disk Error' '-l' 'Hardware' '-n' 'Hardware' '-o' 'SNMP OK - "There are no failed disks."' '-r' 'https://discord.com/api/webhooks/xxxx/xxxx' '-s' 'OK' '-t' 'CUSTOM' '-u' 'DISK OK' '-v' 'false'`

error

curl: (22) The requested URL returned error: 400
[Webhook]: Unable to send webhook.

`'/etc/icinga2/scripts/discord-service-notification.sh' '-4' '1.1.1.1' '-6' '' '-b' 'admin' '-c' 'test' '-d' '2022-09-19 15:05:45 +0300' '-e' 'Disk Error' '-l' 'Hardware' '-n' 'Hardware' '-o' 'SNMP OK - There are no failed disks.' '-r' 'https://discord.com/api/webhooks/xxxx/xxxx' '-s' 'OK' '-t' 'CUSTOM' '-u' 'DISK OK' '-v' 'false'`

send ok

**Comment by ihseko** [comment]
quickly solve

SERVICEOUTPUT=$(echo "${SERVICEOUTPUT}" | sed ':a;N;$!ba;s/\n/, /g')

SERVICEOUTPUT=$(echo "${SERVICEOUTPUT}" | sed ':a;N;$!ba;s/\n/, /g' | sed 's/\"//g')

**Comment by n1tr0-5urf3r** [comment]
> quickly solve
> 
> SERVICEOUTPUT=$(echo "${SERVICEOUTPUT}" | sed ':a;N;$!ba;s/\n/, /g')
> 
> SERVICEOUTPUT=$(echo "${SERVICEOUTPUT}" | sed ':a;N;$!ba;s/\n/, /g' | sed 's/"//g')

Ty for the find and fix, will investigate! I assume the failure results from having quotes in the payload?

**Comment by n1tr0-5urf3r** [comment]
should be fixed in 0dd2e399b724b8144701afe0ae011a61783e01c0
